defaults:
  seed: 0

# specifics about experiment that will be logged to telegram
description: "Segmentation of lesions on t1-weighted MRI"


########################################################
################### Dataset settings ###################
########################################################

datasets:
  # Steps per epoch for each dataset. Total steps = steps_per_epoch * len(datasets.list)
  steps_per_epoch: 92  # 183 samples

  list:
    - id: 0
      name: atlas                        # Used to get NameDataset from data/name_dataset.py
      root: '/home/vladislav/data/ATLAS_R1.1'
      use_to_train: True
      use_to_validate: True

      pre_transforms: []
      augmentations: []
      post_transforms: # 197, 233, 189
        - name: Crop3d
          size: [ 192, 224, 189 ]
        - name: Resize3d
          size: [ 192, 224, 192 ]
        - name: ToTensor3D


dataloader:
  num_workers: 4
  batch_size: 2
  pin_memory: True

########################################################
#################### Model settings ####################
########################################################

model:
  name: 'Unet'
  n_dim: 3
  pipeline: 'multi_task_segmentation'
  params: {'encoder_name': 'resnet50', 'in_channels': 1}

  activations_checkpointing: True

  # Also works for regression
  classification:
    default_criterion:
      cls: 'torch.nn.BCEWithLogitsLoss'

    heads: []

  segmentation:
    default_criterion:
      cls: 'pytorch_toolbelt.losses.SoftCrossEntropyLoss'
      smooth_factor: 0.1

    heads:
      - datasets_ids: [0]
        target: 'mask_atlas'

        # In lightning module metrics will have name {target}@{metric_name}
        metrics: [
          { 'name': 'intersection_over_union', 'num_classes': 2,
            'thresholds': [0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5] },
        ]

        head: 'conv_upsample'
        params:
          classes: 2
          kernel_size: 3

        criterion:
          cls: 'pytorch_toolbelt.losses.JointLoss'
          first:
            cls: 'pytorch_toolbelt.losses.JaccardLoss'
            mode: 'multiclass'
          second:
            cls: 'pytorch_toolbelt.losses.FocalLoss'



optimizer: [{
  'cls': 'torch.optim.Adam',
  'lr': 0.0001
}]

# For some schedulers, you need to rewrite the place where it is called
scheduler: [{
  'cls': 'torch.optim.lr_scheduler.CosineAnnealingWarmRestarts',
  'T_0': 2, 'T_mult': 2
}]

########################################################
################## Training settings ###################
########################################################

callbacks: [
  {'name': 'ModelCheckpoint', 'monitor': 'mask_atlas@intersection_over_union', 'mode': 'max', 'save_last': False, 'save_top_k': 1},
  {'name': 'EarlyStopping', 'monitor': 'valid_loss', 'mode': 'min', 'patience': 15},
  ]

logging:
  name: null   # [null | csv_logs | mlflow | neptune | comet | tensorboard | test_tube | swandb]
  params: {}

# You can add any argument for pytorch_lightning.Trainer
lightning:
  gpus: 1
  num_nodes: 1

# Parameters defined in stages are used to update fields defined above
train_stages:
  - name: training
    lightning:
      max_epochs: 20