defaults:
  seed: 0

# specifics about experiment that will be logged to telegram
description: "Pretraining of segmentation model using several datasets."


########################################################
################### Dataset settings ###################
########################################################

datasets:
  # Steps per epoch for each dataset. Total steps = steps_per_epoch * len(datasets.list)
  steps_per_epoch: 5

  list:
    - id: 0
      name: hippocampus
      root: '/home/vladislav/data/hippocampus'
      use_to_train: True
      use_to_validate: False

      pre_transforms: []

      augmentations: []

      post_transforms:
        - name: Resize3d
          size: [64, 64, 64]
        - name: ToTensor3D

    - id: 1
      name: prostate
      root: '/home/vladislav/data/prostate'
      use_to_train: True
      use_to_validate: True

      pre_transforms: [ ]

      augmentations: [ ]

      post_transforms:
        - name: Resize3d
          size: [128, 128, 32]
        - name: ToTensor3D

dataloader:
  num_workers: 5
  batch_size: 5
  pin_memory: True

########################################################
#################### Model settings ####################
########################################################

model:
  name: 'SegNet'
  n_dim: 3
  pipeline: 'multi_task_segmentation'
  params: {'encoder_name': 'resnet34', 'in_channels': 1}

  classification:
    heads: []

  segmentation:
    default_criterion:
      cls: 'pytorch_toolbelt.losses.SoftCrossEntropyLoss'
      smooth_factor: 0.1

    heads:
      - datasets_ids: [0]
        target: 'mask_hippocampus'

#        # In lightning module metrics will have name {target}@{metric_name}
#        metrics: [
#          { 'name': 'intersection_over_union', 'num_classes': 3, 'threshold': 0.5 },
#        ]

        head: 'conv_upsample'
        params:
          classes: 3


      - datasets_ids: [ 1 ]
        target: 'mask_prostate'       # Train samples - 24

        # In lightning module metrics will have name {target}@{metric_name}
        metrics: [
          { 'name': 'intersection_over_union', 'num_classes': 3, 'threshold': 0.5 },
        ]

        head: 'conv_upsample'
        params:
          classes: 3


optimizer: [{
  'cls': 'torch.optim.Adam',
  'lr': 0.001
}]

# For some schedulers, you need to rewrite the place where it is called
scheduler: [{
  'cls': 'torch.optim.lr_scheduler.ReduceLROnPlateau',
  'patience': 3,
}]

########################################################
################## Training settings ###################
########################################################

callbacks: [
  {'name': 'ModelCheckpoint', 'monitor': 'mask_prostate@intersection_over_union', 'mode': 'max', 'save_last': False, 'save_top_k': 1},
  {'name': 'EarlyStopping', 'monitor': 'valid_loss', 'mode': 'min', 'patience': 10},
  ]

logging:
  name: null   # [null | csv_logs | mlflow | neptune | comet | tensorboard | test_tube | swandb]
  params: {}

# You can add any argument for pytorch_lightning.Trainer
lightning:
  gpus: 1
  num_nodes: 1

# Parameters defined in stages are used to update fields defined above
train_stages:
  - name: res-64
    lightning:
      max_epochs: 50