defaults:
  seed: 0

########################################################
################### Dataset settings ###################
########################################################

dataset:
  name: prostate                        # Used to get NameDataset from data/name_dataset.py
  root: '/home/vladislav/data/hippocampus'
  steps_per_epoch: 50

  pre_transforms: []

  augmentations: []

  post_transforms: [{'name': 'Resize3d', 'size': [32, 32, 32]}, { 'name': 'ToTensor' }]


dataloader:
  num_workers: 2
  batch_size: 10
  pin_memory: True

########################################################
#################### Model settings ####################
########################################################

model:
  name: 'resnet18'
  dim: 3
  pipeline: 'segmentation'      # [segmentation]
  params: {'in_channels': 1, 'num_classes': 1}

criterion: [{
  'cls': 'pytorch_toolbelt.losses.FocalLoss',
  'gamma': 3
}]


optimizer: [{
  'cls': 'torch.optim.Adam',
  'lr': 0.001
}]

# For some schedulers, you need to rewrite the place where it is called
scheduler: [{
  'cls': 'torch.optim.lr_scheduler.CosineAnnealingWarmRestarts',
  'T_0': 2, 'T_mult': 2
}]

########################################################
################## Training settings ###################
########################################################

checkpointing:
  save_top_k: 1
  save_last: False
  mode: 'max'           # if 'max' then bigger metric is better.

  metric:
    name: 'intersection_over_union'
    threshold: 0.5

logging:
  name: null   # [null | csv_logs | mlflow | neptune | comet | tensorboard | test_tube | swandb]
  params: {}
  metrics: [
    {'name': 'intersection_over_union', 'threshold': 0.5}
  ]

# You can add any argument for pytorch_lightning.Trainer
lightning:
  gpus: 1
  num_nodes: 1

# Parameters defined in stages are used to update fields defined above
train_stages:
  - name: training
    lightning:
      max_epochs: 20